package org.talend.bank;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanSimulator implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public LoanSimulator() {
    }

}